#logging:
#  level:
#    root: info
#    org.lzq.nyy.service.Impl: debug
#  file:
#    name: logs/application.log
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
